SSMW-327 tests: Start NVM Daemon
Start the NVM Daemon if present.

Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>

diff --git a/tests/scripts/run_psa_test.sh.in b/tests/scripts/run_psa_test.sh.in
--- a/tests/scripts/run_psa_test.sh.in
+++ b/tests/scripts/run_psa_test.sh.in
@@ -18,12 +18,42 @@ fi
 #
 export SMW_CONFIG_FILE="${cfg_path}/$1"
 
+#
+# Check if the ELE Daemon is present
+# If not active, start it
+#
+if [[ -e /etc/systemd/system/nvm_daemon.service ]]; then
+  res=$(systemctl is-active nvm_daemon)
+  if [[ ${res} != "active" ]]; then
+    systemctl start nvm_daemon
+    res=$(systemctl is-active nvm_daemon)
+    if [[ ${res} != "active" ]]; then
+      echo "NVM Daemon start failure"
+      systemctl -l status nvm_daemon
+      exit 1
+    fi
+  fi
+fi
+
 @PROJECT_NAME@
 res=$?
 if [ $res -ne 0 ]
 then
   echo "$2 test failed (${res})"
   error=1
+fi
+
+if [[ -e /etc/systemd/system/nvm_daemon.service ]]; then
+  res=$(systemctl is-active nvm_daemon)
+  if [[ ${res} == "active" ]]; then
+    systemctl stop nvm_daemon
+    res=$(systemctl is-active nvm_daemon)
+    if [[ ${res} == "active" ]]; then
+      echo "NVM Daemon stop failure"
+      systemctl -l status nvm_daemon
+      error=1
+    fi
+  fi
 fi
 
 exit ${error}
