LF-7508 tests: Do not start NVM Daemon on i.MX9x
If device is i.MX9x don't start NVM Daemon.

Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>

diff --git a/tests/scripts/run_psa_test.sh.in b/tests/scripts/run_psa_test.sh.in
--- a/tests/scripts/run_psa_test.sh.in
+++ b/tests/scripts/run_psa_test.sh.in
@@ -22,15 +22,18 @@ export SMW_CONFIG_FILE="${cfg_path}/$1"
 # Check if the ELE Daemon is present
 # If not active, start it
 #
-if [[ -e /etc/systemd/system/nvm_daemon.service ]]; then
-  res=$(systemctl is-active nvm_daemon)
-  if [[ ${res} != "active" ]]; then
-    systemctl start nvm_daemon
+mach=$(uname -n)
+if [[ "${mach^^}" != *"MX9"* ]]; then
+  if [[ -e /etc/systemd/system/nvm_daemon.service ]]; then
     res=$(systemctl is-active nvm_daemon)
     if [[ ${res} != "active" ]]; then
-      echo "NVM Daemon start failure"
-      systemctl -l status nvm_daemon
-      exit 1
+      systemctl start nvm_daemon
+      res=$(systemctl is-active nvm_daemon)
+      if [[ ${res} != "active" ]]; then
+        echo "NVM Daemon start failure"
+        systemctl -l status nvm_daemon
+        exit 1
+      fi
     fi
   fi
 fi
